language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: "Unit Tests"
      name: "Unit Tests"
      script: npm run test:unit
    - stage: "Integration Tests"
      name: "Integration Tests"
      script: npm run test:int
